# Generated by Django 6.0.2 on 2026-04-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteAppApi', '0007_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='text',
        ),
    ]
