# Generated by Django 6.0.2 on 2026-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteAppApi', '0008_remove_lecture_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
