# Generated by Django 6.0.2 on 2026-04-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteAppApi', '0009_lecture_audio_file_lecture_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_title', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_text', models.TextField(blank=True, null=True)),
                ('youtube_link', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tutorials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
