# Generated by Django 6.0.2 on 2026-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0013_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free Trial"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
