# Generated by Django 6.0.2 on 2026-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0014_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paystack_subscription_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
