# Generated by Django 6.0.2 on 2026-08-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0015_subscription_paystack_subscription_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
