# Generated by Django 6.0.2 on 2026-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0017_subscription_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paystack_email_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
