# Generated by Django 6.0.2 on 2026-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0019_quiz_quizquestion_quizanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
