# Generated by Django 6.0.2 on 2026-09-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0020_lecture_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "start_time", "order"],
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="todo_list",
        ),
        migrations.AddField(
            model_name="task",
            name="week_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="week_start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="todo_title",
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="one_active_task_per_user",
            ),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="NoteAppApi.task",
            ),
        ),
    ]
