# Generated by Django 6.0.2 on 2026-09-11 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0021_taskitem_remove_task_todo_list_task_week_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="one_active_task_per_user",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="week_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="week_start",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False), ("is_deleted", False)),
                fields=("user",),
                name="one_active_task_per_user",
            ),
        ),
    ]
