# Generated by Django 6.0.2 on 2026-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "NoteAppApi",
            "0022_remove_task_one_active_task_per_user_task_completed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
