# Generated by Django 6.0.2 on 2026-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteAppApi", "0023_lecture_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
